version: '3'
services:
  backend:
    build: ./docker
    container_name: backend
    ports:
      - 8000:8000
  frontend:
    build: ./docker
    container_name: frontend
    ports:
      - 8501:8501
